// mod types;
// mod strings;
// mod tuples;
// mod arrays;
// mod arrays;
// mod vectors;
// mod conditional;
// mod loops;
// mod functions;
// mod pointer_ref;
// mod structs;
// mod enums;
// mod cls;
// mod reference;
// mod pass_by_reference;
// mod implement_traits;
// mod read_file;
// mod write_to_file;
// mod define_trains;
// mod pattern_match;
// mod reading_user_input;
// mod hash_map;
// mod random_number;
// mod str_methods;
// mod regex;
// mod modules_use;
// mod http_request;
// mod exec_cmd;
// mod running_test;
mod json_parse;

fn main() {
    // print::run();
    // types::run();
    // vectors::run();
    // loops::run();
    // functions.run();
    // pointer_ref::run();
    // structs::run();
    // enums::run();
    // cls::run();
    // reference::run();
    // pass_by_reference::run();
    // implement_traits::run();
    // read_file::run();
    // write_to_file::run();
    // define_trains::run();
    // pattern_match::run();
    // reading_user_input::run();
    // hash_map::run();
    // random_number::run();
    // modules_use::run();
    // option_use::run();
    // http_request::run();
    // exec_cmd::run();
    // running_test::run();
    json_parse::run();
}

